/**
 * Extracts a few Microsoft Fluent Emoji (Flat, MIT license) as inline SVG strings for the UI.
 * Run: bun scripts/build-icons.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';

const ICONS = [
  'light-bulb', 'coin', 'star', 'glowing-star', 'locked', 'fire', 'crown', 'trophy', 'sparkles', 'gear',
  'house', 'world-map', 'party-popper', 'money-bag', 'check-mark-button', 'cross-mark', 'lady-beetle',
  'crescent-moon', 'sun', 'wrapped-gift', 'red-heart', 'musical-note', 'speaker-high-volume', 'muted-speaker',
  // kitchen
  'fork-and-knife-with-plate', 'cooking', 'bellhop-bell', 'open-book', 'green-book', 'cook', 'hot-beverage',
  'pizza', 'spaghetti', 'hamburger', 'taco', 'croissant', 'steaming-bowl', 'dumpling', 'curry-rice', 'cupcake',
  'tomato', 'cheese-wedge', 'egg', 'onion', 'carrot', 'potato', 'mushroom', 'garlic', 'hot-pepper', 'bread',
  'baguette-bread', 'shortcake', 'teacup-without-handle', 'rice-ball', 'cut-of-meat', 'leafy-green', 'lemon',
  'herb', 'sparkling-heart', 'smiling-face-with-heart-eyes', 'face-savoring-food', 'thinking-face',
];

const set = JSON.parse(readFileSync('node_modules/@iconify-json/fluent-emoji-flat/icons.json', 'utf8'));
const out: Record<string, string> = {};
for (const name of ICONS) {
  let icon = set.icons[name];
  let key = name;
  if (!icon && set.aliases?.[name]) {
    key = set.aliases[name].parent;
    icon = set.icons[key];
  }
  if (!icon) throw new Error('missing icon ' + name);
  const w = icon.width ?? set.width;
  const h = icon.height ?? set.height;
  out[name] = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${icon.left ?? 0} ${icon.top ?? 0} ${w} ${h}">${icon.body}</svg>`;
}
const src =
  '// Generated by scripts/build-icons.ts from Microsoft Fluent Emoji (Flat), MIT License.\n' +
  '// https://github.com/microsoft/fluentui-emoji\n' +
  `export const EMOJI = ${JSON.stringify(out, null, 0)} as const;\n` +
  'export type EmojiName = keyof typeof EMOJI;\n';
writeFileSync('src/ui/emoji.generated.ts', src);
console.log('wrote', Object.keys(out).length, 'icons,', src.length, 'bytes');
